version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: sema-postgres
    environment:
      POSTGRES_DB: semaDb
      POSTGRES_USER: sema_user
      POSTGRES_PASSWORD: sema_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U sema_user -d sema']
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
